
name: MVS/CE Sysgen

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
# Sysgen
  mvsce-sysgen:
    name: MVS 3.8j System Generation
    runs-on: [ubuntu-latest]
    #timeout-minutes: 70
    container: 
      image: mainframed767/hercules:4.7.0
      volumes:
        - /mvsce:/mvsce
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Move MVS/CE sysgen
        run: |
          mv * /mvsce/
        shell: bash
      - name: Set up Python 3
        run: |
          apt-get update
          apt-get -yq install --no-install-recommends python3 python3-pip git

      - name: Building MVS/CE
        id: sysgen
        working-directory: /mvsce
        run: until ./sysgen.py --release --timeout 500 --version ${GITHUB_SHA} --CONTINUE; do echo "Failed, rerunning"; done

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest MVS/CE Sysgen Build"
          files: |
            /mvsce/MVSCE/README.md
            /mvsce/MVSCE.release.*.tar
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          config: .github/buildkitd.toml
          file: ./Docker/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: mainframed767/mvsce:latest